# Generated by Django 4.1.4 on 2022-12-11 21:27

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), common.validators.validate_only_letters])),
                ('car_model', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), common.validators.validate_only_letters])),
                ('engine_type', models.CharField(choices=[('GS', 'Gasoline'), ('DS', 'Diesel'), ('EL', 'Electric'), ('HB', 'Hybrid')], default='GS', max_length=30)),
                ('price', models.IntegerField(max_length=30, validators=[common.validators.validate_integer])),
                ('mileage', models.IntegerField(max_length=30, validators=[common.validators.validate_integer])),
                ('model_year', models.IntegerField(max_length=30, validators=[common.validators.validate_integer])),
                ('current_location', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('contact_number', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('picture', models.URLField()),
                ('description', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
