# Generated by Django 4.1.4 on 2022-12-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_car_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingFavorite',
        ),
    ]
